swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "192.168.7.128:8989"
basePath: "/"
tags:
- name: "user"
  description: "用户管理"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
- name: "products"
  description: "产品管理"
- name: "store"
  description: "库存管理"
  
schemes:
- "http"

paths:
  /user/login:
    post:
      tags:
      - "user"
      summary: "用户登入"
      description: "登入"
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "登入帐户"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
  /products/:
    get:
      tags:
      - "products"
      summary: "获取库存货品清单"
      produces:
      - "application/json"
      parameters: []  
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            required: 
              - "code"
              - "message"
              - "data"
            properties: 
              code: 
                type: "string"
              message: 
                type: "string"
              data: 
                $ref: "#/definitions/Product"
    post:
      tags:
      - "products"
      summary: "添加货品"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "add"
        required: true
        schema:
            type: "object"
            required: 
              - "code"
              - "message"
              - "data"
            properties: 
              code: 
                type: "string"
              message: 
                type: "string"
              data: 
                $ref: "#/definitions/Product"
      responses:
        default:
          description: "successful operation"
  /stores:
    get:
      tags:
      - "store"
      summary: "获取库存"
      produces:
      - "application/json"
      parameters: []  
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            required: 
              - "code"
              - "message"
              - "data"
            properties: 
              code: 
                type: "string"
              message: 
                type: "string"
              data: 
                $ref: "#/definitions/Stores"
          
  
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
    
definitions:
  User:
    type: "object"
    properties:
      loginID:
        type: "string"
      password:
        type: "string"
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      spec:
        type: 'string'
      weight:
        type: 'string'
      remark:
        type: 'string'
  Stores:
    type: "array"
    items:
      $ref: "#/definitions/Store"
  Store:
    type: "object"
    required: 
    - "id"
    - "productID"
    - "productName"
    - "productSpec"
    - "total"
    - "remark"
    - "updateDate"
    properties: 
      id: 
        type: "number"
      productID: 
        type: "number"
      productName: 
        type: "string"
      productSpec: 
        type: "string"
      total: 
        type: "number"
      remark: 
        type: "string"
      updateDate: 
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"